# Generated by Django 2.2.6 on 2019-10-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='created_by',
            new_name='owner',
        ),
    ]
